### ISSUE TITLE
'peer' (a nil value)

### ISSUE THREAD

**Issue by makorne** [tarantool/websocket#10]
Почему-то оба примера клиента(echo & gnax) дают ошибку:

`LuajitError: /home/git/.rocks/share/tarantool/websocket/init.lua:37: attempt to index local 'peer' (a nil value)
fatal error, exiting the event loop
`

Даже если увеличить timeout до 30, пробовать ws или подключаться к запущенному примеру сервера.

`tarantool -v
Tarantool 2.3.1-37-g14842b883
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/lib/ccache/g++
C_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.3.1.37=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.3.1.37=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-cast-function-type
`

**Comment by filonenko-mikhail** [comment]
В них используется ssl
- client.lua пофиксил
- gdax.lua нет
  - gdax требует force tlsv1.3 пока не понял как его включить
