### ISSUE TITLE
ssl socket not work on OpenSSL 1.1.x

### ISSUE THREAD

**Issue by norguhtar** [tarantool/websocket#5]
problem:
```
.rocks/share/tarantool/websocket/ssl.lua:96: tarantool: undefined symbol: SSL_library_init
```

ffi use deprecation function for init ssl and crypto.

These methods deprecated and should be removed
```
 const SSL_METHOD *SSLv23_method(void);
 const SSL_METHOD *SSLv23_server_method(void);
 const SSL_METHOD *SSLv23_client_method(void);

 const SSL_METHOD *SSLv3_method(void);
 const SSL_METHOD *SSLv3_server_method(void);
 const SSL_METHOD *SSLv3_client_method(void);

 void SSL_load_error_strings(void);
```
This method deprecated
```
int SSL_library_init(void);
```
Replaced by this method:
```
typedef struct ossl_init_settings_st OPENSSL_INIT_SETTINGS;
int OPENSSL_init_ssl(uint64_t opts, const OPENSSL_INIT_SETTINGS *settings);
```

**Comment by dimtos** [comment]
Same issue.
What is the solution to the problem?

Tarantool 2.4.0-20-g05d3ed4b0
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/lib/ccache/g++
C_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.4.0.20=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.4.0.20=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-cast-function-type

**Comment by torwig** [comment]
This works for me:
* remove from `ssl.lua` lines:

 `const SSL_METHOD *SSLv23_method(void);`
 `const SSL_METHOD *SSLv23_server_method(void);`
 `const SSL_METHOD *SSLv23_client_method(void);`
 `const SSL_METHOD *SSLv3_method(void);`
 `const SSL_METHOD *SSLv3_server_method(void);`
 `const SSL_METHOD *SSLv3_client_method(void);`

` int SSL_library_init(void);`
 `void SSL_load_error_strings(void);`

`ffi.C.SSL_library_init()`
`ffi.C.SSL_load_error_strings()`

`sslv23 = ffi.C.SSLv23_method(),` -- in `local methods`
`sslv3 = ffi.C.SSLv3_method(),`  -- in `local methods`

* in function `ctx(method)` change line `method = method or ffi.C.SSLv23_method()` to `method = method or ffi.C.TLSv1_1_method()`

**Comment by filonenko-mikhail** [comment]
updated

**Comment by filonenko-mikhail** [comment]
fixed
