### ISSUE TITLE
Нет тестов для frame.BINARY

### ISSUE THREAD

**Issue by makorne** [tarantool/websocket#7]
Почему-то нет тестов для этого режима, есть только для

`opcode=websocket.TEXT`

Может, это значит что BINARY здесь использовать незачем и файлы, например картинки - нужно передавать в режиме TEXT ?

**Comment by filonenko-mikhail** [comment]
BINARY можно пользоваться, просто руки не дошли сделать тест

**Comment by filonenko-mikhail** [comment]
Сделал тест - закрывая
